export enum ActionType {
  MESSAGE = "MESSAGE",
  LOADING = "LOADING",
  SET_MESSAGE = "SET_MESSAGE",
  SET_LOADING = "SET_LOADING",
  SET_COLLECTIONS = "SET_COLLECTIONS",
  FETCH_COLLECTIONS = "FETCH_COLLECTIONS",
  SET_PAGE = "SET_PAGE",
  SET_NEXT_PAGE = "SET_NEXT_PAGE",
  SET_CURRENT_COLLECTIONS = "SET_CURRENT_COLLECTIONS",
}
