export enum ActionType {
  MESSAGE = "MESSAGE",
  LOADING = "LOADING",
  SET_MESSAGE = "SET_MESSAGE",
  SET_LOADING = "SET_LOADING",
  FETCH_PROJECTS = "FETCH_PROJECTS",
  SET_PROJECTS = "SET_PROJECTS",
  SET_PAGE = "SET_PAGE",
  SET_NEXT_PAGE = "SET_NEXT_PAGE",
  SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT",
}
