export enum ActionType {
  MESSAGE = "MESSAGE",
  LOADING = "LOADING",
  SET_MESSAGE = "SET_MESSAGE",
  SET_LOADING = "SET_LOADING",
  FETCH_TEAMS = "FETCH_TEAMS",
  SET_TEAMS = "SET_TEAMS",
  SET_PAGE = "SET_PAGE",
  SET_NEXT_PAGE = "SET_NEXT_PAGE",
  SET_CURRENT_TEAMS = "SET_CURRENT_TEAMS",
}
